backend:
  name: git-gateway
  branch: develop

# アップロードされた画像ファイルのパス
media_folder: "site/static/img"
# アップロードされた画像ファイルの場所
public_folder: "/img"
# ワークフローの追加
publish_mode: editorial_workflow
# 公開サイトのURL
site_url: https://cherryerc-homepage-dev.netlify.com
# サイト編集画面に表示されるリンク
display_url: https://cherryerc-homepage-dev.netlify.com
# ログイン画面のロゴ
logo_url: https://cherryerc-homepage-dev.netlify.com/admin/logo.png
# 言語設定
locale: "ja"

collections:

  - label: "ブログ" # 管理画面のサイドバーで使う
    name: "blog" # 管理画面のパスで使う　例：/admin/collections/blog
    folder: "site/content/blog" # Markdownを保存するディレクトリ。Hugoのsectionにあたる
    filter: {field: "type", value: "blog"}
    create: true # 新しいページを作ることを許可する
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Markdownのファイル名　例：YYYY-MM-DD-title.md
    fields: # ページ作成画面で使う。Front Matterの値を書く
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "公開日", name: "date", widget: "datetime" }
      - { label: "サムネイル画像", name: "thumbnail", widget: "image" }
      - { label: "本文", name: "body", widget: "markdown" }
      - { label: "type", name: "type", widget: "hidden", default: "blog"}

  - label: "ページ"
    name: "page"
    files:
      - file: "site/content/_index.md"
        label: "ホームページ"
        name: "home"
        fields:
          - { tabel: "タイトル", name: "title", widget: "string" }
          - { label: "本文", name: "body", widget: "markdown" }
      - file: "site/content/experience/_index.md"
        label: "体験レッスン"
        name: "experience"
        fields:
          - { tabel: "タイトル", name: "title", widget: "string" }
          - { label: "本文", name: "body", widget: "markdown" }
      - file: "site/content/products/_index.md"
        label: "教室紹介"
        name: "products"
        fields:
          - { tabel: "タイトル", name: "title", widget: "string" }
          - { label: "本文", name: "body", widget: "markdown" }
      - file: "site/content/events/_index.md"
        label: "イベント"
        name: "events"
        fields:
          - { tabel: "タイトル", name: "title", widget: "string" }
          - { label: "本文", name: "body", widget: "markdown" }
      - file: "site/content/blog/_index.md"
        label: "ブログ一覧"
        name: "blog"
        fields:
          - { tabel: "タイトル", name: "title", widget: "string" }
          - { label: "本文", name: "body", widget: "markdown" }
      - file: "site/content/contact/_index.md"
        label: "お問い合わせ"
        name: "contact"
        fields:
          - { tabel: "タイトル", name: "title", widget: "string" }
          - { label: "本文", name: "body", widget: "markdown" }
      - file: "site/content/thankyou/_index.md"
        label: "送信完了画面"
        name: "thankyou"
        fields:
          - { tabel: "タイトル", name: "title", widget: "string" }
          - { label: "本文", name: "body", widget: "markdown" }    