backend:
  name: git-gateway
  branch: develop

# アップロードされた画像ファイルのパス
media_folder: "site/static/img"
# アップロードされた画像ファイルの場所
public_folder: "/img"
# 公開サイトのURL
site_url: https://cherryerc-homepage-dev.netlify.com
# サイト編集画面に表示されるリンク
display_url: https://cherryerc-homepage-dev.netlify.com
# ログイン画面のロゴ
#logo_url: https://exsample.com/logo.svg
# 言語設定
locale: "ja"

collections:
  - label: "ページ"
    name: "page"
    files:

      - labal: "ホーム"
        name: "home"
        file: "site/content/_index.md"
        create: false
        fields:
          - { tabel: "タイトル", name: "title", widget: "string" }
          - { label: "本文", name: "body", widget: "markdown" }

      - label: "体験レッスン"
        name: "experience"
        file: "site/content/experience/_index.md"
        create: false
        fields:
          - { tabel: "タイトル", name: "title", widget: "string" }
          - { label: "本文", name: "body", widget: "markdown" }

      - label: "教室紹介"
        name: "products"
        file: "site/content/products/_index.md"
        create: false
        fields:
          - { tabel: "タイトル", name: "title", widget: "string" }
          - { label: "本文", name: "body", widget: "markdown" }

      - label: "イベント"
        name: "events"
        file: "site/content/events/_index.md"
        create: false
        fields:
          - { tabel: "タイトル", name: "title", widget: "string" }
          - { label: "本文", name: "body", widget: "markdown" }

      - label: "お問い合わせ"
        name: "contact"
        file: "site/content/contact/_index.md"
        create: false
        fields:
          - { tabel: "タイトル", name: "title", widget: "string" }
          - { label: "本文", name: "body", widget: "markdown" }

      - label: "送信完了ページ"
        name: "thankyou"
        file: "site/content/thankyou/_index.md"
        create: false
        fields:
          - { tabel: "タイトル", name: "title", widget: "string" }
          - { label: "本文", name: "body", widget: "markdown" }

  - label: "ブログ" # 管理画面のサイドバーで使う
    name: "blog" # 管理画面のパスで使う　例：/admin/collections/blog
    folder: "site/content/blog" # Markdownを保存するディレクトリ。Hugoのsectionにあたる
    create: true # 新しいページを作ることを許可する
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Markdownのファイル名　例：YYYY-MM-DD-title.md
    editor:
      preview: false
    fields: # ページ作成画面で使う。Front Matterの値を書く
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "公開日", name: "date", widget: "datetime" }
      - { label: "サムネイル画像", name: "thumbnail", widget: "image" }
      - { label: "本文", name: "body", widget: "markdown" }


